[[foobar]]
arch = "x86_64"
git-tree-sha1 = "9a8dfae78dac5de25e62705aa4017b399e267160"
libc = "glibc"
os = "linux"

    [[foobar.download]]
    sha256 = "60b18f02898da60102bc22b8f6c488e5d176453b23071b19731797f5caf31f47"
    url = "file:/Users/erikengheim/Development/Julia/ArchExperiments/foobar-lin.tar.gz"
    
[[foobar]]
arch = "x86_64"
git-tree-sha1 = "70d6addecf4f1e67ac4470ee9839bcb07e19d773"
os = "windows"

    [[foobar.download]]
    sha256 = "8dea794ca27ac15ea09712a0d3249450f047f21f6534b9624d6cba79463ade0b"
    url = "file:/Users/erikengheim/Development/Julia/ArchExperiments/foobar-win.tar.gz"

[[foobar]]
arch = "x86_64"
git-tree-sha1 = "5fc005bfb4a5436fcde1cc097be47a3f323b8a14"
os = "macos"

    [[foobar.download]]
    sha256 = "5c50e53d0d3878105fa5f52e1e543664c45a209d182b5a57ebd352d7b6d3c9b3"
    url = "file:/Users/erikengheim/Development/Julia/ArchExperiments/foobar-mac.tar.gz"